a=int(input("Insira um valor: "))
b=int(input("Insira um valor: "))
c=int(input("Insira um valor: "))
d=int(input("Insira um valor: "))
adicao=(a+b)+(a+c)+(a+d)+(b+c)+(b+d)+(c+d)
multiplicacao=(a*b)+(a*c)+(a*d)+(b*c)+(b*d)+(c*d)
print("Adição: ",adicao,"\nMultiplicação: ",multiplicacao)
